jedi/urls.py
from django.contrib import admin
from django.urls import path
from jedi_manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),

]

jedi_manager/urls.py
from django.urls import path
from .views import IndexView
from .views import create_candidate #, candidates_list, CandidateDetail

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

]

# app_name = 'candidates'
#
# urlpatterns = [
#     path('create', create_candidate, name='create'),
#     # path('list', candidates_list, name='list'),
#     # path('<int:pk>', CandidateDetail.as_view(), name='detail')
# ]

jedi_manager/models.py
from django.db import models


class Planet(models.Model):
    """Планета"""
    name = models.CharField(max_length=100, default='', verbose_name='Название')

    class Meta:
        verbose_name = 'Планета'
        verbose_name_plural = 'Планеты'

    def __str__(self):
        return self.name


class Jedi(models.Model):
    """Джедай"""
    name = models.CharField(max_length=100, default='', verbose_name='Имя')
    planet = models.ForeignKey(Planet, on_delete=models.SET_NULL, null=True, verbose_name='Планета')

    class Meta:
        verbose_name = 'Джедай'
        verbose_name_plural = 'Джедаи'

    def __str__(self):
        return self.name

    # def add_padawan(self, candidate):
    #     candidate.jedi = self
    #     candidate.save()
    #     candidate.make_padawan()


class Candidate(models.Model):
    """ Кандидат """
    name = models.CharField(max_length=80)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField()
    email = models.EmailField()
    jedi = models.ForeignKey(Jedi, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Кандидат'
        verbose_name_plural = 'Кандидаты'


class Questions(models.Model):
    """ Модель для вопросов """
    content = models.CharField(max_length=240)
    right_answer = models.BooleanField()

    def __str__(self):
        return self.content[:50]

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class PadawanTest(models.Model):
    """ Модель тестового испытания падавана """
    planet = models.OneToOneField(Planet, on_delete=models.CASCADE)
    questions = models.ManyToManyField(Questions)

    def __str__(self):
        return "{} order challenge".format(self.planet)


class Answers(models.Model):
    """ Модель для ответов """
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    questions = models.ForeignKey(Questions, on_delete=models.CASCADE)
    content = models.BooleanField()

jedi_manager/views.py
from django.shortcuts import render


def index(request):
    """
    Выводит на экран 2 кнопки: Для Джедаи, Для кандидата.
    """
    return render(request, "index.html")

templates/jedi_manager/candidate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Для кандидатов</title>

</head>
<body  bgcolor="#181513">
<font color="#c0c0c0">
     <header>
        <center>
            <h2 onclick="window.location='/index'">
                STAR WARS
            </h2>
        </center>
    </header>
    <center>
    <form method="POST" action="candidate">{% csrf_token %}
        <table>
            <tr>
                <td colspan="2" align="center">
                    Заполните форму
                </td>
            </tr>
            <tr>
                <td>
                    <label>Введите свою планету</label><br>
                </td>
                <td>
                    <select id="p" name="planet">
                        {% for p in planet %}
                        <option value={{p.id}}>{{ p.name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Введите email</label><br>
                </td>
                <td>
                    <input type="text" name="email" />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Введите имя</label><br>
                </td>
                <td>
                    <input type="text" name="name" />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Введите возраст</label><br>
                </td>
                <td>
                    <input type="number" name="age" />
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" value="Далее" >
                </td>
            </tr>
        </table>
    </form>
</center>
</font>
</body>
</html>

templates/jedi_manager/djedai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Для джедаев</title>
    <style type="text/css">
    HEADER {
    width: 100%; height: 70px;
    background: #181513; /*  фона */
    border: 2px solid #fc0; /* рамка */
    }
    H2 {
    font-size: 150%;
    }
    TABLE {
    width: 300px;
    border-collapse: collapse;
    }
    TD, TH {
    padding: 7px;
    border: 2px solid #fc0;
    }
  </style>
</head>
<body bgcolor="#181513">
<font color="#c0c0c0">
    <header>
        <center>
            <h2 onclick="window.location='/index'">
                STAR WARS
            </h2>
        </center>
    </header>
    <form method="POST" action="djedai">{% csrf_token %}
        <table>
            <tr><th colspan="2">Фильтры для кандидатов</th></tr>
            <tr><th>Имя</th><th><input type="text" name="name_filter" value="{{filter_name}}"/></th></tr>
            <tr><th>Мин возраст</th><th><input type="number" name="age_filter" value="{{filter_age}}"/></th></tr>
            <tr><th colspan="2"><input type="submit" value="Применить"></th></tr>
        </table>
        <center>
            <input type="hidden" name="selected_jedi" value="{{selected_jedi}}">
            <h2>Список кандидатов</h2>
            <table>
                <tr><th>Имя</th><th>Возраст</th><th>тест</th><th>email</th></tr>
                {% csrf_token %}
                {% for candidate in list_candidate %}
                <tr>
                    <td>{{ candidate.name }}</td>
                    <td>{{ candidate.age }}</td>
                    <td><a href="watchtest/{{candidate.id}}/">Резултат</a></td>
                    <td>{{ candidate.email }}</td>
                    <td><a href="send/{{master_jedi}}/{{candidate.id}}/">Взять в падаваны</a></td>
                </tr>
                {% endfor %}
            </table>
        </center>
    </form>
</font>
</body>
</html>

templates/jedi_manager/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Академия джедаев</title>
</head>
<font color="#c0c0c0">
    <body class="container" >
     <center >
      <h1>
          <button onclick="window.location='/masterJedi'" class="still">Для Джедаев</button>
          <button onclick="window.location='/candidate'" class="still">Для кандидатов</button>
      </h1>
  </center>
</body>
</font>
</html>

templates/jedi_manager/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поздравляю</title>
    <style type="text/css">
    HEADER {
    width: 100%; height: 70px;
    background: #181513; /*  фона */
    border: 2px solid #fc0; /* рамка */
    }
    H2 {
    font-size: 150%;
    }
    TABLE {
    margin-top: 10%;
    width: 300px;
    border-collapse: collapse;
    }
    TD, TH {
    font-size: 50px;
    padding: 10px;
    white-space: nowrap;
    }
  </style>
</head>
<body bgcolor="#181513">
<font color="#c0c0c0">
    <header>
        <center>
            <h2 onclick="window.location='/index'">
                STAR WARS
            </h2>
        </center>
    </header>
    <center>
        <table>
            <tr>
                <td>
                    {{ text }}
                </td>
            </tr>
        </table>
    </center>
</font>
</body>
</html>

templates/jedi_manager/master_jedai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Представьтесь</title>
    <style type="text/css">
    HEADER {
    width: 100%; height: 70px;
    background: #181513; /*  фона */
    border: 2px solid #fc0; /* рамка */
    }
    H2 {
    font-size: 150%;
    }
    TABLE {
    width: 300px;
    border-collapse: collapse;
    }
    TD, TH {
    padding: 10px;
    border: 2px solid #fc0;
    }
  </style>
</head>
<body bgcolor="#181513">
<font color="#c0c0c0">
    <header>
        <center>
            <h2 onclick="window.location='/index'">
                STAR WARS
            </h2>
        </center>
    </header>
    <form method="POST" action="masterJedi">{% csrf_token %}
        <table>
            <tr><th>Мин кол-во учеников</th><th><input type="number" name="min_number_of_students" min="0" value="{{min_number_of_students}}"/></th></tr>
            <tr><th colspan="2"><input type="submit" value="Применить" ></th></tr>
        </table>
    </form>
    <form method="POST" action="djedai">{% csrf_token %}
        <center>
            <table>
                <tr><th colspan="3">
                    <select id="djs" name="selected_jedi">
                        {% for jedi in all_jedi %}
                        <option value={{jedi.id}}>{{ jedi.name }}</option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Выбрать" >
                </tr></th>
                <tr><th>Джедай</th><th>Ученики</th><th>Планета обитания</th></tr>
                {% for jedi in list_jedi %}
                <tr>
                    <td>{{ jedi.name }}</td>
                    <td nowrap>
                        {% for pupils in  jedi.candidate_set.all %}
                          {{ pupils.name }}<br>
                        {% endfor %}
                    </td>
                    <td>{{ jedi.planet.name }}</td>
                </tr>
                {% endfor %}
            </table>
        </center>
    </form>
</font>
</body>
</html>

templates/jedi_manager/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Тест</title>
    <style>
        FIELDSET {
        border: 2px solid #fc0;
        }
    </style>
</head>border: 2px solid #c0c0c0;
<body bgcolor="#181513">
<font color="#c0c0c0">
    <center>
    <form method="POST" action="test" >{% csrf_token %}
        {% for Question in Questions %}
        <fieldset>
            <legend><p><b>{{ Question.text }}</b></p></legend>
            {% for Answer in Answers %}
            {% if Answer.question == Question %}
            <p><input name={{Question.id}} type="radio" value={{Answer.id}} checked> {{ Answer.text }} </p>
            {% endif%}
            {% endfor %}
        </fieldset>
        {% endfor %}
        <input name="candidate_id" type="hidden" value={{candidate_id}}>
        <input type="submit" value="дальше" >
    </form>
    </center>
</font>
</body>
</html>

templates/jedi_manager/watch_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результаты теста</title>
    <style type="text/css">
    HEADER {
    width: 100%; height: 70px;
    background: #181513; /*  фона */
    border: 2px solid #fc0; /* рамка */
    }
    H2 {
    font-size: 150%;
    }
    TABLE {
    width: 300px;
    border-collapse: collapse;
    }
    TD, TH {
    padding: 7px;
    border: 2px solid #fc0;
    }
</style>
</head>
<body bgcolor="#181513">
<font color="#c0c0c0">
<header>
        <center>
            <h2 onclick="window.location='/index'">
                STAR WARS
            </h2>
        </center>
</header>
    <center>
        <h2>{{ candidate_name }}</h2>
        <table>
            <tr><th>Вопрос</th><th>Ответ</th></tr>
            {% for test in test_list %}
            <tr>
                <td>{{ test.test_question.text }}</td>
                <td>{{ test.test_answer.text }}</td>
            </tr>
            {% endfor %}
            <tr><th>Всего вопросов: {{ question }}</th><th nowrap>Правильных: {{ answer }}</th></tr>
        </table>
    </center>
</font>
</body>
</html>